workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        NODE_VERSION: "20"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Setup Node.js
        script: |
          . ~/.nvm/nvm.sh
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
          node --version
      - name: Install npm dependencies
        script: |
          . ~/.nvm/nvm.sh
          nvm use $NODE_VERSION
          npm install
      - name: Build web assets
        script: |
          . ~/.nvm/nvm.sh
          nvm use $NODE_VERSION
          npm run build
      - name: Copy Capacitor assets
        script: |
          . ~/.nvm/nvm.sh
          nvm use $NODE_VERSION
          npx cap copy ios
      - name: Install CocoaPods
        script: |
          cd ios/App && pod repo update && pod install
      - name: Build iOS App
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/App/build/**/*.xcarchive

  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      vars:
        NODE_VERSION: "20"
      java: 17
    scripts:
      - name: Setup Node.js
        script: |
          . ~/.nvm/nvm.sh
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
          node --version
      - name: Install npm dependencies
        script: |
          . ~/.nvm/nvm.sh
          nvm use $NODE_VERSION
          npm install
      - name: Build web assets
        script: |
          . ~/.nvm/nvm.sh
          nvm use $NODE_VERSION
          npm run build
      - name: Sync Capacitor
        script: |
          . ~/.nvm/nvm.sh
          nvm use $NODE_VERSION
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
      - name: Build Android Bundle (AAB)
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
